# klasa odpowiedzialna za wyglad aplikacji
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
import ctypes
class Ui_MainWindow(QtWidgets.QMainWindow): 
    def setupUi(self, MainWindow):
        myappid = u'wat.analizakluczowychczynnikow.zarzadzanie' # arbitrary string
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
        self.icon = QtGui.QIcon()
        self.icon.addFile("img/icon16x16.png", QtCore.QSize(16,16))
        self.icon.addFile("img/icon24x24.png", QtCore.QSize(24,24))
        self.icon.addFile("img/icon32x32.png", QtCore.QSize(32,32))
        self.icon.addFile("img/icon48x48.png", QtCore.QSize(48,48))
        self.icon.addFile("img/icon255x255.png",QtCore.QSize(255,255))
        self.setWindowIcon(self.icon)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 707)
        self.setFixedSize(1075, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.przyciskOdswiez = QtWidgets.QPushButton(self.centralwidget)
        self.przyciskOdswiez.setGeometry(QtCore.QRect(580, 670, 88, 27))
        self.przyciskOdswiez.setObjectName("przyciskOdswiez")
        self.wykresGlowny = QtWidgets.QFrame(self.centralwidget)
        self.wykresGlowny.setGeometry(QtCore.QRect(-1, -1, 631, 661))
        self.wykresGlowny.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresGlowny.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresGlowny.setObjectName("wykresGlowny")
        self.wykresGlowny.setLayout(QtWidgets.QVBoxLayout())
        self.wykresPrawyGora = QtWidgets.QFrame(self.centralwidget)
        self.wykresPrawyGora.setGeometry(QtCore.QRect(620, 0, 451, 331))
        self.wykresPrawyGora.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresPrawyGora.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresPrawyGora.setObjectName("wykresPrawyGora")
        self.wykresPrawyGora.setLayout(QtWidgets.QVBoxLayout())
        self.wykresPrawyDol = QtWidgets.QFrame(self.centralwidget)
        self.wykresPrawyDol.setGeometry(QtCore.QRect(620, 320, 451, 341))
        self.wykresPrawyDol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresPrawyDol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresPrawyDol.setObjectName("wykresPrawyDol")
        self.wykresPrawyDol.setLayout(QtWidgets.QVBoxLayout())
        self.przyciskEdytuj = QtWidgets.QPushButton(self.centralwidget)
        self.przyciskEdytuj.setGeometry(QtCore.QRect(420, 670, 151, 27))
        self.przyciskEdytuj.setObjectName("przyciskEdytuj")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.menubar.setPalette(palette)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setObjectName("menubar")
        self.menuDane = QtWidgets.QMenu(self.menubar)
        self.menuDane.setObjectName("menuDane")
        self.menuEksportuj = QtWidgets.QMenu(self.menuDane)
        self.menuEksportuj.setObjectName("menuEksportuj")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWykresGlowny = QtWidgets.QAction(MainWindow)
        self.actionWykresGlowny.setObjectName("actionWykresGlowny")
        self.actionWykresPrawyGora = QtWidgets.QAction(MainWindow)
        self.actionWykresPrawyGora.setObjectName("actionWykresPrawyGora")
        self.actionWykresPrawyDol = QtWidgets.QAction(MainWindow)
        self.actionWykresPrawyDol.setObjectName("actionWykresPrawyDol")
        self.actionImportuj = QtWidgets.QAction(MainWindow)
        self.actionImportuj.setObjectName("actionImportuj")
        self.menuEksportuj.addAction(self.actionWykresGlowny)
        self.menuEksportuj.addAction(self.actionWykresPrawyDol)
        self.menuDane.addAction(self.menuEksportuj.menuAction())
        self.menuDane.addAction(self.actionImportuj)
        self.menubar.addAction(self.menuDane.menuAction())
        self.set_listeners(MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def view_starting_popup(self):  #dodac mozliwosc ze arkusz juz istnieje
        start_dialog = QtWidgets.QDialog()
        label = QtWidgets.QLabel()
        label.setAlignment(QtCore.Qt.AlignLeft)
        label.setText("Witaj!\nProgram wygenerował dla Ciebie arkusz Excel\nw którym możesz dodać informacje potrzebne\ndo przeprowadzenia analizy.")
        label.setFont(QtGui.QFont("Calibri", 10))
        #label.setFont(QtGui.QFont("Arial", 11))
        label.move(50,50)
        popup_button = QtWidgets.QPushButton()
        popup_button.setText("OK")
        popup_button.clicked.connect(self.zamknij_okienko)
        popup_layout = QtWidgets.QVBoxLayout()
        popup_layout.addWidget(label)
        popup_layout.addWidget(popup_button)
        start_dialog.setLayout(popup_layout)
        start_dialog.setWindowTitle("Informacja")
        start_dialog.setWindowIcon(self.icon)
        start_dialog.show()
        start_dialog.exec_()

    def view_duplicate_names_alert(self):
        alert_dialog = QtWidgets.QDialog()
        label = QtWidgets.QLabel()
        label.setAlignment(QtCore.Qt.AlignLeft)
        label.setText("W pliku excel znajdują się dane o zduplikowanych nazwach. Zmień nazwy firm lub czynników, aby wygenerowane wykresy były poprawne, po czym kliknij przycisk \"Odśwież\".")
        label.move(50,50)
        popup_button = QtWidgets.QPushButton()
        popup_button.setText("OK")
        popup_button.clicked.connect(self.zamknij_okienko)
        popup_layout = QtWidgets.QVBoxLayout()
        popup_layout.addWidget(label)
        popup_layout.addWidget(popup_button)
        alert_dialog.setLayout(popup_layout)
        alert_dialog.setWindowTitle("Informacja")

        alert_dialog.show()
        alert_dialog.exec_()
    def zamknij_okienko(self):
        QtCore.QCoreApplication.instance().quit()

    def open_file(self, file = "nazwa_firmy.xlsx"):
        if sys.platform == 'linux2':
            subprocess.call(["xdg-open", file])
        else:
            os.startfile(file)
    def set_listeners(self, MainWindow):
        self.actionImportuj.triggered.connect(MainWindow.otworz_wybrany_excel)
        self.actionWykresGlowny.triggered.connect(MainWindow.eksportuj_wykres_glowny)
        self.actionWykresPrawyDol.triggered.connect(MainWindow.eksportuj_wykres_kolowy)
        self.przyciskEdytuj.clicked.connect(MainWindow.edytuj_excel)
        self.przyciskOdswiez.clicked.connect(MainWindow.odswiez)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analiza Kluczowych Czynników Sukcesu"))
        self.przyciskOdswiez.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Naciśnij kiedy zapiszesz uzupełniony arkusz.</p></body></html>"))
        self.przyciskOdswiez.setText(_translate("MainWindow", "Odśwież"))
        self.przyciskEdytuj.setText(_translate("MainWindow", "Edytuj Arkusz"))
        self.menuDane.setTitle(_translate("MainWindow", "Dane"))
        self.menuEksportuj.setTitle(_translate("MainWindow", "Eksportuj"))
        self.actionWykresGlowny.setText(_translate("MainWindow", "Wykres główny"))
        self.actionWykresPrawyGora.setText(_translate("MainWindow", "Wykres słupkowy"))
        self.actionWykresPrawyDol.setText(_translate("MainWindow", "Wykres kołowy"))
        self.actionImportuj.setText(_translate("MainWindow", "Importuj"))
        self.actionImportuj.setWhatsThis(_translate("MainWindow", "Kliknij jeżeli w folderze programu znajduje się arkusz o nazwie \"Dane.xlsx\""))
