# klasa odpowiedzialna za wyglad aplikacji
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
class Ui_MainWindow(QtWidgets.QMainWindow): 
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 707)
        self.setFixedSize(1075, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.przyciskOdswiez = QtWidgets.QPushButton(self.centralwidget)
        self.przyciskOdswiez.setGeometry(QtCore.QRect(580, 670, 88, 27))
        self.przyciskOdswiez.setObjectName("przyciskOdswiez")
        self.przyciskOdswiez.clicked.connect(MainWindow.odswiez)
        self.wykresGlowny = QtWidgets.QFrame(self.centralwidget)
        self.wykresGlowny.setGeometry(QtCore.QRect(-1, -1, 631, 671))
        self.wykresGlowny.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresGlowny.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresGlowny.setObjectName("wykresGlowny")
        self.wykresPrawyGora = QtWidgets.QFrame(self.centralwidget)
        self.wykresPrawyGora.setGeometry(QtCore.QRect(620, 0, 451, 331))
        self.wykresPrawyGora.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresPrawyGora.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresPrawyGora.setObjectName("wykresPrawyGora")
        self.wykresPrawyDol = QtWidgets.QFrame(self.centralwidget)
        self.wykresPrawyDol.setGeometry(QtCore.QRect(630, 330, 451, 341))
        self.wykresPrawyDol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wykresPrawyDol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wykresPrawyDol.setObjectName("wykresPrawyDol")
        self.przyciskEdytuj = QtWidgets.QPushButton(self.centralwidget)
        self.przyciskEdytuj.setGeometry(QtCore.QRect(420, 670, 151, 27))
        self.przyciskEdytuj.setObjectName("przyciskEdytuj")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.menubar.setPalette(palette)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setObjectName("menubar")
        self.menuDane = QtWidgets.QMenu(self.menubar)
        self.menuDane.setObjectName("menuDane")
        self.menuEksportuj = QtWidgets.QMenu(self.menuDane)
        self.menuEksportuj.setObjectName("menuEksportuj")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)        
        self.actionImport.setObjectName("actionImport")
        self.actionWykresy = QtWidgets.QAction(MainWindow)
        self.actionWykresy.setObjectName("actionWykresy")
        self.actionArkusz = QtWidgets.QAction(MainWindow)
        self.actionArkusz.setObjectName("actionArkusz")
        self.actionArkusz.triggered.connect(MainWindow.zapisz_aktualny_arkusz)
        self.actionImportuj = QtWidgets.QAction(MainWindow)
        self.actionImportuj.setObjectName("actionImportuj")
        self.actionImportuj.triggered.connect(MainWindow.otworz_wybrany_excel)
        self.menuEksportuj.addAction(self.actionWykresy)
        self.menuEksportuj.addAction(self.actionArkusz)
        self.menuDane.addAction(self.menuEksportuj.menuAction())
        self.menuDane.addAction(self.actionImportuj)
        self.menubar.addAction(self.menuDane.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def view_starting_popup(self):  #dodac mozliwosc ze arkusz juz istnieje
        start_dialog = QtWidgets.QDialog()
        label = QtWidgets.QLabel()
        label.setAlignment(QtCore.Qt.AlignLeft)
        label.setText("Witaj!\nProgram wygenerował dla Ciebie arkusz Excel\nw którym możesz dodać informacje potrzebne\ndo przeprowadzenia analizy.")
        label.move(50,50)
        popup_button = QtWidgets.QPushButton()
        popup_button.setText("OK")
        popup_button.clicked.connect(self.zamknij_okienko)
        popup_layout = QtWidgets.QVBoxLayout()
        popup_layout.addWidget(label)
        popup_layout.addWidget(popup_button)
        start_dialog.setLayout(popup_layout)
        start_dialog.setWindowTitle("Informacja")
        start_dialog.show()
        start_dialog.exec_()

    def zamknij_okienko(self):
        QtCore.QCoreApplication.instance().quit()

    def open_file(self, file = "nazwa_firmy.xlsx"):
        if sys.platform == 'linux2':
            subprocess.call(["xdg-open", file])
        else:
            os.startfile(file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analiza Kluczowych Czynników Sukcesu"))
        self.przyciskOdswiez.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Naciśnij kiedy zapiszesz uzupełniony arkusz.</p></body></html>"))
        self.przyciskOdswiez.setText(_translate("MainWindow", "Odśwież"))
        self.przyciskEdytuj.setText(_translate("MainWindow", "Edytuj Arkusz"))
        self.menuDane.setTitle(_translate("MainWindow", "Dane"))
        self.menuEksportuj.setTitle(_translate("MainWindow", "Eksportuj"))
        self.actionImport.setText(_translate("MainWindow", "Importuj"))
        self.actionWykresy.setText(_translate("MainWindow", "Wykresy"))
        self.actionArkusz.setText(_translate("MainWindow", "Arkusz"))
        self.actionImportuj.setText(_translate("MainWindow", "Importuj"))
        self.actionImportuj.setWhatsThis(_translate("MainWindow", "Kliknij jeżeli w folderze programu znajduje się arkusz o nazwie \"Dane.xlsx\""))
