# klasa odpowiedzialna za wyglad aplikacji
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
from ctypes import windll
class Ui_MainWindow(QtWidgets.QMainWindow): 
    def setupUi(self, MainWindow):
        myappid = u'wat.analizakluczowychczynnikow.zarzadzanie' # arbitrary string
        windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
        self.icon = QtGui.QIcon()
        self.icon.addFile("img/icon16x16.png", QtCore.QSize(16,16))
        self.icon.addFile("img/icon24x24.png", QtCore.QSize(24,24))
        self.icon.addFile("img/icon32x32.png", QtCore.QSize(32,32))
        self.icon.addFile("img/icon48x48.png", QtCore.QSize(48,48))
        self.icon.addFile("img/icon255x255.png",QtCore.QSize(255,255))
        self.setWindowIcon(self.icon)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 707)
        self.setFixedSize(1075, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(580, 670, 88, 27))
        self.refreshButton.setObjectName("refreshButton")
        self.mainPlot = QtWidgets.QFrame(self.centralwidget)
        self.mainPlot.setGeometry(QtCore.QRect(-1, -1, 631, 661))
        self.mainPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPlot.setObjectName("mainPlot")
        self.mainPlot.setLayout(QtWidgets.QVBoxLayout())
        self.barChart = QtWidgets.QFrame(self.centralwidget)
        self.barChart.setGeometry(QtCore.QRect(620, 0, 451, 331))
        self.barChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barChart.setObjectName("barChart")
        self.barChart.setLayout(QtWidgets.QVBoxLayout())
        self.pieChart = QtWidgets.QFrame(self.centralwidget)
        self.pieChart.setGeometry(QtCore.QRect(620, 320, 451, 341))
        self.pieChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pieChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pieChart.setObjectName("pieChart")
        self.pieChart.setLayout(QtWidgets.QVBoxLayout())
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(420, 670, 151, 27))
        self.editButton.setObjectName("editButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 100, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.menubar.setPalette(palette)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setObjectName("menubar")
        self.manuData = QtWidgets.QMenu(self.menubar)
        self.manuData.setObjectName("manuData")
        self.exportMenu = QtWidgets.QMenu(self.manuData)
        self.exportMenu.setObjectName("exportMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMainPlot = QtWidgets.QAction(MainWindow)
        self.actionMainPlot.setObjectName("actionMainPlot")
        self.actionBarChart = QtWidgets.QAction(MainWindow)
        self.actionBarChart.setObjectName("actionBarChart")
        self.actionPieChart = QtWidgets.QAction(MainWindow)
        self.actionPieChart.setObjectName("actionPieChart")
        self.actionBarChart = QtWidgets.QAction(MainWindow)
        self.actionBarChart.setObjectName("actionBarChart")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.exportMenu.addAction(self.actionMainPlot)
        self.exportMenu.addAction(self.actionBarChart)
        self.exportMenu.addAction(self.actionPieChart)
        self.manuData.addAction(self.exportMenu.menuAction())
        self.manuData.addAction(self.actionImport)
        self.menubar.addAction(self.manuData.menuAction())
        self.set_listeners(MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def view_starting_popup(self):  
        start_dialog = QtWidgets.QDialog()
        label = QtWidgets.QLabel()
        label.setAlignment(QtCore.Qt.AlignLeft)
        label.setText("Witaj!\nProgram wygenerował dla Ciebie arkusz Excel\nw którym możesz dodać informacje potrzebne\ndo przeprowadzenia analizy.")
        label.setFont(QtGui.QFont("Calibri", 10))
        #label.setFont(QtGui.QFont("Arial", 11))
        label.move(50,50)
        popup_button = QtWidgets.QPushButton()
        popup_button.setText("OK")
        popup_button.clicked.connect(self.close_window)
        popup_layout = QtWidgets.QVBoxLayout()
        popup_layout.addWidget(label)
        popup_layout.addWidget(popup_button)
        start_dialog.setLayout(popup_layout)
        start_dialog.setWindowTitle("Informacja")
        start_dialog.setWindowIcon(self.icon)
        start_dialog.show()
        start_dialog.exec_()

    '''
    Yet to be used, but not absolutely necessary...
    '''
    def view_duplicate_names_alert(self):
        alert_dialog = QtWidgets.QDialog()
        label = QtWidgets.QLabel()
        label.setAlignment(QtCore.Qt.AlignLeft)
        label.setText("W pliku excel znajdują się dane o zduplikowanych nazwach. Zmień nazwy firm lub czynników, aby wygenerowane wykresy były poprawne, po czym kliknij przycisk \"Odśwież\".")
        label.move(50,50)
        popup_button = QtWidgets.QPushButton()
        popup_button.setText("OK")
        popup_button.clicked.connect(self.close_window)
        popup_layout = QtWidgets.QVBoxLayout()
        popup_layout.addWidget(label)
        popup_layout.addWidget(popup_button)
        alert_dialog.setLayout(popup_layout)
        alert_dialog.setWindowTitle("Informacja")

        alert_dialog.show()
        alert_dialog.exec_()
    def close_window(self):
        QtCore.QCoreApplication.instance().quit()

    def open_file(self, file = "nazwa_firmy.xlsx"):
        if sys.platform == 'linux2':
            subprocess.call(["xdg-open", file])
        else:
            os.startfile(file)
    def set_listeners(self, MainWindow):
        self.actionImport.triggered.connect(MainWindow.open_given_xl)
        self.actionMainPlot.triggered.connect(MainWindow.export_main_plot)
        self.actionPieChart.triggered.connect(MainWindow.export_pie_chart)
        self.actionBarChart.triggered.connect(MainWindow.export_bar_chart)
        self.editButton.clicked.connect(MainWindow.edit_xl)
        self.refreshButton.clicked.connect(MainWindow.refresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analiza Kluczowych Czynników Sukcesu"))
        self.refreshButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Naciśnij kiedy zapiszesz uzupełniony arkusz.</p></body></html>"))
        self.refreshButton.setText(_translate("MainWindow", "Odśwież"))
        self.editButton.setText(_translate("MainWindow", "Edytuj Arkusz"))
        self.manuData.setTitle(_translate("MainWindow", "Dane"))
        self.exportMenu.setTitle(_translate("MainWindow", "Eksportuj"))
        self.actionMainPlot.setText(_translate("MainWindow", "Wykres główny"))
        self.actionBarChart.setText(_translate("MainWindow", "Wykres słupkowy"))
        self.actionPieChart.setText(_translate("MainWindow", "Wykres kołowy"))
        self.actionBarChart.setText(_translate("MainWindow", "Wykres słupkowy"))
        self.actionImport.setText(_translate("MainWindow", "Importuj"))
        self.actionImport.setWhatsThis(_translate("MainWindow", "Kliknij jeżeli w folderze programu znajduje się arkusz o nazwie \"Dane.xlsx\""))
